### ISSUE TITLE
HTTP wrapper does not support writeable connections

### ISSUE THREAD

**Issue by wings77** [daniloaz/myphp-backup#12]
Hello Daniel,

this error 

> Warning: file_put_contents(http://wampserver/htdocs/erp/backups/1-backup-softnet_alladin_demo-20190519_120856.sql): failed to open stream: HTTP wrapper does not support writeable connections in D:\wampserver\htdocs\erp\demo\core\class_database\myphp-backup.php on line 304

on line...

`file_put_contents($this->backupDir.'/'.$this->backupFile, $sql, FILE_APPEND | LOCK_EX);`

**Comment by daniloaz** [comment]
You can not write directly to an HTTP endpoint (you should use a WebDAV for that). Backup dir and backup file must be an absolute or relative path within your storage disk, not an HTTP URL.
