### ISSUE TITLE
Question: Cronjobs

### ISSUE THREAD

**Issue by nelsondcosta23** [daniloaz/myphp-backup#3]
I tested the script, its awesome it works perfectly fine.
But when I tried to use a cron job on it, well nothing happens, can you help?

**Comment by daniloaz** [comment]
Thank you Nelson. Could you show me your cron job to try to figure out what's going on?

**Comment by nelsondcosta23** [comment]
Im so sorry daniloaz, it was my fault.

Evertthing works, its 5 stars :)
