### ISSUE TITLE
Having issue while merging both rrestore and backup file

### ISSUE THREAD

**Issue by vsfarooqkhan** [daniloaz/myphp-backup#7]
Hey , Im having an issue when I tried to merge both backup and restore file with in a same file, 
I tried to give inputs (db name, username , password in input fields and manual sql file upload)
. 
I couldn't able to call a particular function, because there are several functions writen for every single work ,.  I want to create a single function,  and need to make backup codes within a single function. is this possible?

**Comment by daniloaz** [comment]
Hi vsfarooqkhan, everything is possible adapting the code properly, but these scripts are designed to work independently of each other as they can run in different servers and to be easy to understand by making use of functions and some OOP concepts, so I think the changes you propose are out of the scope of this project. In any case, thank you for your feedback.
