### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by lenamtl** [daniloaz/myphp-backup#8]
Hi,

Should we set a timezone  for  the timestamp data or this is not required?

The first backup the timestamps was not ok then I made other tests and the timestamp are ok so
 I'm not sure if there is a real problem and cannot reproduce

**Comment by daniloaz** [comment]
Hi lenamtl, this is not required. PHP takes timezone information from the server by default, so it is not necessary to specify a timezone. But if for whatever reason you need it, you can add the P flag to date() function's format or force an arbitrary timezone using the date_timezone_set() function.
